### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by AshleighAdams** [AshleighAdams/Verlite#28]
Instead of specifying all options thru CLI args or MsBuild properties, it may be beneficial to have a yml Verlite can point to instead, so CI/CD verlites, such as autofetching, won't need to by synced up.

**Comment by AshleighAdams** [comment]
This could be done at the consumer end with something akin to:

```xml
<VerliteMinimumVersion>$([System.IO.File]::ReadAllText("MinVersion.txt"))</VerliteMinimumVersion>
```

No need for Verlite to take on this complexity, would you agree @Victormeriqui?

**Comment by Victormeriqui** [comment]
> This could be done at the consumer end with something akin to:
> 
> ```
> <VerliteMinimumVersion>$([System.IO.File]::ReadAllText("MinVersion.txt"))</VerliteMinimumVersion>
> ```
> 
> No need for Verlite to take on this complexity, would you agree @Victormeriqui?

Agreed, it's a nice feature but goes a bit against being lightweight 😅
